import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { SessionSummary } from "@/store/session-store";
import { formatINR } from "./format";

export function generateReceipt(summary: SessionSummary) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(249, 115, 22); // orange-500
  doc.rect(0, 0, pageWidth, 36, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text("SmartCart", 14, 18);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Shopping Receipt", 14, 27);
  doc.text(new Date().toLocaleDateString("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  }), pageWidth - 14, 18, { align: "right" });

  if (summary.id) {
    doc.setFontSize(8);
    doc.text(`Session #${summary.id}`, pageWidth - 14, 27, { align: "right" });
  }

  // Summary boxes
  let y = 46;
  doc.setTextColor(100, 100, 100);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");

  const boxW = (pageWidth - 42) / 3;
  const boxes = [
    { label: "Total Spent", value: formatINR(summary.totalSpent) },
    { label: "Items", value: String(summary.itemCount) },
    { label: "Budget", value: summary.budget > 0 ? formatINR(summary.budget) : "—" },
  ];

  boxes.forEach((b, i) => {
    const x = 14 + i * (boxW + 7);
    doc.setDrawColor(229, 231, 235);
    doc.roundedRect(x, y, boxW, 18, 2, 2, "S");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.text(b.label, x + 4, y + 7);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(17, 24, 39);
    doc.text(b.value, x + 4, y + 14);
  });

  y += 28;

  // Items table
  const tableBody = summary.items.map((item, i) => [
    String(i + 1),
    item.name,
    item.category,
    String(item.quantity),
    formatINR(item.price),
    formatINR(item.price * item.quantity),
  ]);

  autoTable(doc, {
    startY: y,
    head: [["#", "Item", "Category", "Qty", "Unit Price", "Total"]],
    body: tableBody,
    theme: "striped",
    headStyles: {
      fillColor: [249, 115, 22],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
    },
    bodyStyles: {
      fontSize: 8.5,
      textColor: [55, 65, 81],
    },
    alternateRowStyles: {
      fillColor: [255, 247, 237],
    },
    margin: { left: 14, right: 14 },
    columnStyles: {
      0: { cellWidth: 10, halign: "center" },
      3: { cellWidth: 14, halign: "center" },
      4: { cellWidth: 26, halign: "right" },
      5: { cellWidth: 26, halign: "right" },
    },
  });

  // Footer total
  const finalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  doc.setDrawColor(229, 231, 235);
  doc.line(14, finalY, pageWidth - 14, finalY);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(17, 24, 39);
  doc.text("Total", 14, finalY + 8);
  doc.text(formatINR(summary.totalSpent), pageWidth - 14, finalY + 8, { align: "right" });

  if (summary.budget > 0) {
    const diff = summary.budget - summary.totalSpent;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    if (diff >= 0) {
      doc.setTextColor(22, 163, 74);
      doc.text(`Under budget by ${formatINR(diff)}`, 14, finalY + 16);
    } else {
      doc.setTextColor(220, 38, 38);
      doc.text(`Over budget by ${formatINR(Math.abs(diff))}`, 14, finalY + 16);
    }
  }

  // Footer branding
  const pageH = doc.internal.pageSize.getHeight();
  doc.setFontSize(7);
  doc.setTextColor(156, 163, 175);
  doc.text("Generated by SmartCart — AI-Powered Shopping Assistant", pageWidth / 2, pageH - 8, { align: "center" });

  // Save
  doc.save(`SmartCart-Receipt-${summary.id ?? Date.now()}.pdf`);
}
