"use strict";

const INTENTS = Object.freeze({
  GREETING: "GREETING",
  SEARCH_PRODUCT: "SEARCH_PRODUCT",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  UPDATE_QUANTITY: "UPDATE_QUANTITY",
  VIEW_CART: "VIEW_CART",
  CHECKOUT: "CHECKOUT",
  CHECK_BUDGET: "CHECK_BUDGET",
  RECOMMEND: "RECOMMEND",
  REORDER: "REORDER",
  UNKNOWN: "UNKNOWN",
});

const ALL_INTENTS = Object.values(INTENTS);

module.exports = { INTENTS, ALL_INTENTS };
